name: Create Release
on: 
  push:
    branches: [master]
  workflow_dispatch:
    
jobs:
  unload-from-folder:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: moves files out of folder
        run: mv ./unoffical-sponge-documentation/* ./..
      - name: removes original folder
        run: rm -r ./unoffical-sponge-documentation
      - name: Commiting to page branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          branch: pages
          push_options: '--force'
          create_branch: true

          
  
